name: Claude Code Assistant

on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  claude:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # prompt: "You are the LiTHePlan assistant..."
          # additional_inputs: "optional custom instructions"
